### PR TITLE
Modified _cffi.py to create bindings for the additional SDL libs (SDL_Image, SDL_Mixer,  SDL_TTF, SDL_gfx).

### PR DESCRIPTION
**Pull request by jdoda**

### CODE REVIEW

**Comment by kahowell** [comment]
Would love to merge this...

Can you take a look at the travis issues? If not, when I have some spare time, I'll take a close look.

**Comment by jdoda** [comment]
Yep, I'll have a look.

On Tue, Jan 12, 2016, at 13:06, Kevin Howell wrote:

> Would love to merge this...
> 
> Can you take a look at the travis issues? If not, when I have some
> spare time, I'll take a close look.
> 
> — Reply to this email directly or view it on GitHub[1].

Links:
1. https://github.com/kahowell/sdl2-cffi/pull/4#issuecomment-170997441

**Comment by jdoda** [comment]
Ok, passing in travis now. Not sure if it'll work with appveyor or not, since I'm not entirely sure how to test that.

**Comment by jdoda** [comment]
Hey, was just wondering if you'd had a chance to look at this again.

**Comment by kahowell** [comment]
Thanks for following up. Will merge momentarily.

**Pull request merged**
